### ISSUE TITLE
[feat] Change the clicking practice of the tray icon to open the clipboard history instead of settings

### ISSUE THREAD

**Issue by ChanceFlow** [ayangweb/EcoPaste#331] opened 2024-08-06 09:25 UTC
### Describe the problem

The current functionality when clicking the tray icon leads to settings. However, this feature proposes a change where clicking the tray icon will now open the clipboard history record. This enhancement aims to provide users with quicker and more direct access to their clipboard history, enhancing the efficiency and usability of the system. For example, when a user is working on multiple tasks that involve frequent copying and pasting, they can easily review the clipboard history by simply clicking the tray icon, instead of having to navigate through multiple menus to reach the settings and then access the clipboard history. Such a change would streamline the user experience and make the process more intuitive and time-saving.

### Describe the solution you'd like

The solution I envision involves reconfiguring the functionality associated with the tray icon. Currently, its default action is to direct users to the settings page. The desired modification would reprogram this icon so that when clicked, it immediately opens the clipboard history record.

**Comment by ayangweb** [comment] 2024-08-06 09:33
Duplicate of #300 

Feedback received, issue duplicated, this issue will be closed and will be supported in the next release!

**Closed by ayangweb** 2024-08-06 09:33 UTC
Labels: type: feature request

**Comment by ayangweb** [comment] 2024-08-06 12:18
#332 Supported and looking forward to the next version!
