### ISSUE TITLE
[bug] 剪切板切换tab滚动条异常

### ISSUE THREAD

**Issue by kohaiy** [ayangweb/EcoPaste#192] opened 2024-07-22 10:04 UTC
### Describe the bug

剪切板【全部】很多数据，滚动到底部，切换tab到较少的tab，滚动条异常
![image](https://github.com/user-attachments/assets/5a03ac0c-78d5-49bd-91fa-c92b86bbc2c5)

### Expected behavior

切换tab后可以滚动到顶部

### Application and system information

```text
{
  "appName": "EcoPaste",
  "appVersion": "0.0.4",
  "tauriVersion": "1.7.1",
  "platform": "Windows_NT",
  "platformArch": "x86_64",
  "platformVersion": "10.0.19045"
}
```

**Comment by ayangweb** [comment] 2024-07-22 10:23
Duplicate of #130 问题重复，此问题已优化！

**Closed by ayangweb** 2024-07-22 10:23 UTC
Labels: type: bug, status: needs triage
