### ISSUE TITLE
[feat] Listening processes can be excluded

### ISSUE THREAD

**Issue by GongLe** [ayangweb/EcoPaste#385] opened 2024-08-18 06:47 UTC
### Describe the problem

Listening processes can be excluded
可在设置中指定排除监听线程名称，避免粘贴板记录垃圾数据，例如不监听截图软件。

### Describe the solution you'd like

参考竞品ditto
![Clip_2024-08-18_14-47-22](https://github.com/user-attachments/assets/25496c49-ce55-42cc-989d-bab88c18dd8f)

### Alternatives considered

参考竞品ditto

**Comment by ayangweb** [comment] 2024-08-19 00:41
Duplicate of #285 

收到反馈，问题重复，此 issue 将被关闭，后续我们会研究此问题的可行性🌹

**Closed by ayangweb** 2024-08-19 00:41 UTC
Labels: type: feature request
