### ISSUE TITLE
点击后直接插入[feat] 

### ISSUE THREAD

**Issue by amaoo** [ayangweb/EcoPaste#109] opened 2024-07-12 08:03 UTC
### Describe the problem

![image](https://github.com/user-attachments/assets/61224f6a-ca59-47ae-b8d3-e3dca4d98a83)

### Describe the solution you'd like

类似于 windows 自带 的  Win + V 快捷键，点击后直接输入

**Comment by ayangweb** [comment] 2024-07-12 08:04
Duplicate of #29 问题重复，期待后续版本支持！也欢迎 pr

**Closed** 2024-07-12 08:05 UTC
Labels: type: feature request

**Comment by ayangweb** [comment] 2024-07-20 17:15
#169 功能已实现，期待下个版本！
